add pop-up specification
samreenmj/Portfolio-mobile--first pull request #9
Opened 2023-03-15 22:51 UTC by samreenmj

added -
When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
When the user clicks (or taps) the close (X) button, the popup disappears.

2023-03-16 08:26 UTC, AlphaNtihinduka reviewed
Hi @samreenmj ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
# Invalid Code Review Request ❌ 

- [x] This is a pair programming milestone. It implies that the contributors should have the commits in this PR. Kindly ensure to contact your collaborator to participate in the project building.
- [ ] In addition, i have noticed that the placeholders have not been customized. Kindly customise them eg: `project not yet deployed`. This will make the project professional.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-03-16 19:32 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @samreenmj , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media2.giphy.com/media/d1E1msx7Yw5Ne1Fe/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters
- [ ].... ✅ Good readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 19:32 UTC, joskalenda commented on test.js
> +                Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
- [x] Dear @samreenmj I appreciate your work after all but there are some issues we need to fix before, the project data should be dynamic for each project but this description is hard coded for all the projects in the popup I think you should use catch this same as you have done for images, technologies and other.
- [x] and it seems to be too long, please reduce the text length to make your design well-aligned.

ORIGINAL

<img width="318" alt="1" src="https://user-images.githubusercontent.com/77843050/225731761-88a3e32a-1c35-41c3-99c2-391bdd78cf55.png">

YOUR DESIGN

![5](https://user-images.githubusercontent.com/77843050/225731823-8148512a-881d-4e81-a19c-262514e61b8a.gif)

DESKTOP

- [x] I think a good pop-up window should not scroll up-down, please make sure you fix your styling to adjust it and make your paragraph in 2 as shown in the original design.

YOUR DESIGN

<img width="1182" alt="2" src="https://user-images.githubusercontent.com/77843050/225732320-d24d8843-31ab-466c-bd8f-2b2b86bf3323.png">

ORIGINAL

<img width="625" alt="3" src="https://user-images.githubusercontent.com/77843050/225732642-4f36bdff-b985-4a63-8d64-ac13f1568d10.png">

2023-03-17 08:40 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @samreenmj, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 13:01 UTC, merged